version: '3.1'

services:

  sqs:
    build: .
    command: consumer
    environment:
      - LOCALSTACK=true
      - SQS_QUEUE_NAME=test-queue
      - SNS_TOPIC_ARN=arn:aws:sns:us-east-1:000000000000:test-topic
      - ENDPOINT_URL=http://localstack:4566
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    depends_on:
      - localstack
      - sns
  
  sns:
    build: .
    command: producer
    environment:
      - LOCALSTACK=true
      - SQS_QUEUE_NAME=test-queue
      - SNS_TOPIC_ARN=arn:aws:sns:us-east-1:000000000000:test-topic
      - ENDPOINT_URL=http://localstack:4566
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:0.12.9
    ports:
      - "4566:4566"
      - "4571:4571"
  
  debug:
    image: amazon/aws-cli
    entrypoint: sleep 1000000000
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - ENDPOINT_URL=http://localstack:4566
